name: Launchable Demo

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_MAVEN }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1
  SMART_TESTS_ORGANIZATION: "cloudbees"
  SMART_TESTS_WORKSPACE: "pts-v2-workshop-klee"

on:
  push:
    branches:
      - main
      
jobs:
  PreMergeTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: "temurin"
      - name: Install dependencies
        run: pip install launchable
      - run: "launchable verify"
      - name: Record commits and build
        run: 'launchable record build --name "$GITHUB_RUN_ID"'
